name: Report de Bug
description: Reportar um problema ou um bug com o pacote
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Lamentamos saber que você tem um problema. Você pode nos ajudar a resolvê-lo fornecendo os seguintes detalhes.
    - type: textarea
      id: what-happened
      attributes:
          label: O que aconteceu?
          description: O que aconteceu exatamente?
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: Como reproduzir o bug
          description: Como isso ocorreu, adicione quaisquer valores de configuração usados e forneça um conjunto de etapas confiáveis, se possível.
      validations:
          required: true
    - type: input
      id: package-version
      attributes:
          label: Versão do pacote
          description: Qual versão do pacote você está utilizando?
          placeholder: 1.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: Versão do PHP
          description: Qual versão do PHP você está utilizando?
          placeholder: 8.1.0
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
          label: Versão do Laravel
          description: Qual versão do Laravel você está utilizando?
          placeholder: 10.0.0
      validations:
          required: true
    - type: dropdown
      id: operating-systems
      attributes:
          label: Com quais sistemas operacionais acontece?
          description: Você pode selecionar mais de um.
          multiple: true
          options:
              - macOS
              - Windows
              - Linux
    - type: textarea
      id: notes
      attributes:
          label: Observações
          description: Use este campo para fornecer quaisquer outras observações que você considere relevantes para o problema.
      validations:
          required: false
