site_name: PagHiper for Laravel
site_description: Integração da PagHiper com Laravel
site_author: AJ Meireles
repo_url: https://github.com/devajmeireles/paghiper-for-laravel/
edit_uri: blob/main/docs/docs
extra_css:
  - css/style.css
theme:
  name: readthedocs
  highlightjs: true
  hljs_style: vs
  hljs_languages:
    - php
    - shell
  locale: pt_BR
  logo: images/logo.png
  collapse_navigation: False
  titles_only: True
  sticky_navigation: False
nav:
    - Boas-vindas: index.md
    - Iniciando:
          - Detalhes Técnicos: iniciando/detalhes-tecnicos.md
          - Instalação: iniciando/instalacao.md
    - Recursos:
          - Boleto Bancário:
                - Criando: recursos/boleto/criando.md
                - Status: recursos/boleto/status.md
                - Cancelando: recursos/boleto/cancelando.md
                - Retorno Automático: recursos/boleto/retorno.md
          - PIX:
                - Criando: recursos/pix/criando.md
                - Status: recursos/pix/status.md
                - Cancelando: recursos/pix/cancelando.md
                - Retorno Automático: recursos/pix/retorno.md
          - Utilidades:
                - Casts: recursos/utilidades/casts.md
    - Tratamento de Erros:
          - Excessões: erros/excessoes.md
    - Repositório:
          - Contribuição: repositorio/contribuicao.md
