site_name: PagHiper for Laravel
site_description: Integração da PagHiper com Laravel
site_author: AJ Meireles
repo_url: https://github.com/devajmeireles/paghiper-for-laravel/
edit_uri: blob/main/docs/docs
extra_css:
  - css/style.css
theme:
  name: readthedocs
  highlightjs: true
  hljs_style: vs2015
  hljs_languages:
    - php
  locale: pt_BR
  logo: images/logo.png
  collapse_navigation: False
  titles_only: True
  sticky_navigation: False
