name: Publish Docs
on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'

jobs:
    build:
        name: Deploy Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@v2

            - name: Deploy Docs
              uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CONFIG_FILE: docs/mkdocs.yml
