name: Publish MkDocs via GitHub Pages
on:
    push:
        branches:
            - "main"
        paths:
            - "docs/**"

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v2

            - name: Install Dependencies
              run: |
                  pip install --upgrade pip
                  pip install mkdocs

#            - name: Setup Git Config
#              run: |
#                  git config user.name 'mkdocs-deploy'
#                  git config user.email 'mkdocs-deploy@noreply.github.com'

            - name: Deploy Docs
              run: mkdocs gh-deploy --config-file docs/mkdocs.yml --remote-branch docs
