name: PestPHP Tests

on:
    push:
        branches:
            - main
            - develop
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches:
            - main
            - develop
            - release/**
        paths-ignore:
            - 'docs/**'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.2, 8.3]
                laravel: ['10.*', '11.*']
                stability: [prefer-stable]
                include:
                    - laravel: 10.*
                      testbench: 8.*
                      carbon: ^2.63
                    - laravel: 11.*
                      testbench: 9.*
                      carbon: ^2.63
                exclude:
                    - laravel: 11.*
                      php: 8.1

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Verifying pint
              run: vendor/bin/pint --test

            - name: Execute tests
              run: vendor/bin/pest --ci --parallel
